export const UPDATE_GRID = "UPDATE_GRID";
export const INCREASE_DENSITY = "INCREASE_DENSITY";
export const DECREASE_DENSITY = "DECREASE_DENSITY";
export const UPDATE_RUN = "UPDATE_RUN";
export const UPDATE_GENERATIONS = "UPDATE_GENERATIONS";
export const UPDATE_SQUARE_SIZE = "UPDATE_SQUARE_SIZE";
