export const UPDATE_GRID = "UPDATE_GRID";
export const INCREASE_ROWS = "INCREASE_ROWS";
export const DECREASE_ROWS = "DECREASE_ROWS";
export const UPDATE_COLUMNS = "UPDATE_COLUMNS";
export const UPDATE_RUN = "UPDATE_RUN";
export const UPDATE_GENERATIONS = "UPDATE_RUN";
