export const UPDATE_GRID = "UPDATE_GRID";
export const INCREASE_ROWS = "INCREASE_ROWS";
export const DECREASE_ROWS = "DECREASE_ROWS";
export const INCREASE_COLUMNS = "INCREASE_COLUMNS";
export const DECREASE_COLUMNS = "DECREASE_COLUMNS";
export const UPDATE_RUN = "UPDATE_RUN";
export const UPDATE_GENERATIONS = "UPDATE_RUN";
export const UPDATE_SQUARE_SIZE = "UPDATE_SQUARE_SIZE";
